version: "3.7"

services:

  server:
    container_name: server
    image: node:latest
    working_dir: '/usr/app'
    command: ["sh", "init.sh"]
    tty: true
    ports: 
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - mysql
    
  phpmyadmin:
    extends:
      file: ../docker-compose.yml
      service: phpmyadmin

  mysql:
    extends:
      file: ../docker-compose.yml
      service: mysql
  
volumes:
  gztech-mysql:
    driver: local